apiVersion: apps/v1
kind: Deployment
metadata:
  name: nasty-deployment
  namespace: nasty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nastycontainer
  template:
    metadata:
      labels:
        app: nastycontainer
    spec:
      containers:
      - name: nastycontainer
        image: bajacloud/nastycontainer:int
        command: ["sleep", "infinity"]
        securityContext:
          privileged: true
