apiVersion: apps/v1
kind: Deployment
metadata:
  name: nasty-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nastycontainer
  template:
    metadata:
      labels:
        app: nastycontainer
    spec:
      containers:
      - name: nastycontainer
        image: bajacloud/nastycontainer:latest  
        securityContext:
          privileged: true  
        volumeMounts:
        - name: host-volume
          mountPath: /host-data  
      volumes:
      - name: host-volume
        hostPath:
          path: /path/to/host/data  

