name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'K8s-manifests/**'
  workflow_dispatch:  # Allows manual triggering from the GitHub Actions UI

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to DockerHub using a safer authentication method
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Determine version tag (semantic versioning + commit SHA)
      - name: Determine Docker Image Version
        id: vars
        run: echo "VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV

      # Build and push the Docker image with multiple tags
      - name: Build and Push Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag bajacloud/nastycontainer:${{ env.VERSION }} \
            --tag bajacloud/nastycontainer:latest \
            --push \
            --file Dockerfile \
            .
